name: syna
channels:
  - pytorch
  - defaults
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=2.16
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - contourpy=1.1.1
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cycler=0.12.1
  - filelock=3.13.1
  - fonttools=4.53.1
  - freetype=2.12.1
  - gmp=6.3.0
  - gmpy2=2.1.2
  - intel-openmp=2023.1.0
  - jinja2=3.1.3
  - kiwisolver=1.4.5
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.8.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.8.0
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.8.1.2
  - libcurand=10.3.4.107
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.20
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=13.2.0
  - libjpeg-turbo=3.0.0
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libnpp=11.7.4.75
  - libnsl=2.0.1
  - libnvjpeg=11.8.0.2
  - libpng=1.6.43
  - libsqlite=3.45.1
  - libstdcxx-ng=13.2.0
  - libtiff=4.6.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libzlib=1.2.13
  - markupsafe=2.1.5
  - matplotlib-base=3.7.3
  - mkl=2020.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.4
  - networkx=3.1
  - openjpeg=2.5.2
  - openssl=3.2.1
  - pip=24.0
  - pthread-stubs=0.4
  - pyparsing=3.1.4
  - python=3.8.15
  - python_abi=3.8
  - pytorch=2.0.0
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - readline=8.2
  - setuptools=69.1.0
  - six=1.16.0
  - sympy=1.12
  - tk=8.6.13
  - torchtriton=2.0.0
  - typing_extensions=4.9.0
  - unicodedata2=15.1.0
  - wheel=0.42.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - aaindex==1.1.2
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - anyio==4.5.2
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.4
      - async-timeout==5.0.1
      - attrs==25.3.0
      - babel==2.17.0
      - backcall==0.2.0
      - beautifulsoup4==4.13.3
      - bleach==6.1.0
      - cachetools==5.3.2
      - captum==0.7.0
      - certifi==2024.2.2
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - click==8.1.7
      - comet-ml==3.28.1
      - comm==0.2.2
      - configobj==5.0.8
      - debugpy==1.8.13
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dill==0.3.9
      - docker-pycreds==0.4.0
      - dulwich==0.21.7
      - et-xmlfile==2.0.0
      - everett==3.3.0
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - gitdb==4.0.11
      - gitpython==3.1.42
      - google-auth==2.28.1
      - google-auth-oauthlib==1.0.0
      - grpcio==1.62.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.29.3
      - idna==3.6
      - importlib-metadata==7.0.1
      - importlib-resources==6.1.1
      - ipykernel==6.29.5
      - ipython==8.12.3
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jedi==0.19.2
      - joblib==1.3.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - lightning-utilities==0.11.9
      - markdown==3.5.2
      - matplotlib-inline==0.1.7
      - mistune==3.1.3
      - multidict==6.1.0
      - multiprocess==0.70.17
      - nbclient==0.10.1
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.3.3
      - notebook-shim==0.2.4
      - numpy==1.23.4
      - nvidia-ml-py3==7.352.0
      - oauthlib==3.2.2
      - openpyxl==3.1.2
      - overrides==7.7.0
      - p-tqdm==1.4.2
      - packaging==23.2
      - pandas==2.0.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pathos==0.3.3
      - pathtools==0.1.2
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.2.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - pox==0.3.5
      - ppft==1.7.6.9
      - prometheus-client==0.21.1
      - promise==2.3
      - prompt-toolkit==3.0.50
      - propcache==0.2.0
      - protobuf==3.20.1
      - protpy==1.2.1
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycparser==2.22
      - pydeprecate==0.3.2
      - pygments==2.19.1
      - python-dateutil==2.8.2
      - python-json-logger==3.3.0
      - pytorch-lightning==1.6.4
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==26.3.0
      - rdkit==2022.9.5
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.3
      - requests-oauthlib==1.3.1
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.20.1
      - rsa==4.9
      - safetensors==0.5.3
      - scikit-learn==1.0.1
      - scipy==1.10.1
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentry-sdk==1.40.5
      - setproctitle==1.3.3
      - shortuuid==1.0.11
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - threadpoolctl==3.3.0
      - tinycss2==1.2.1
      - tokenizers==0.20.3
      - tomli==2.2.1
      - torchmetrics==1.5.2
      - tornado==6.4.2
      - tqdm==4.62.3
      - traitlets==5.14.3
      - transformers==4.46.3
      - types-python-dateutil==2.9.0.20241206
      - tzdata==2025.1
      - uri-template==1.3.0
      - urllib3==2.2.1
      - varname==0.13.5
      - wandb==0.12.19
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.13
      - wrapt==1.16.0
      - wurlitzer==3.0.3
      - yarl==1.15.2
      - zipp==3.17.0
